# Site settings
title: Edison Hsu Blog
email: 263113565#qq.com
description: > # this means to ignore newlines until "baseurl:"
  Edison Hsu's Personal Blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.edison-hsu.com" # the base hostname & protocol for your site
twitter_username: _Edison_Hsu_
github_username:  Edison-Hsu

timezone: 'China/Shanghai'

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
